spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=false

spring.jpa.properties.hibernate.format_sql=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

server.forward-headers-strategy=framework

server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

logging.level.root=INFO
logging.level.org.springframework=WARN
logging.level.org.hibernate=WARN
logging.level.com.sophia=INFO

logging.level.org.springframework.boot.autoconfigure.security=ERROR

management.endpoints.web.exposure.include=health,info,prometheus

management.endpoint.health.show-details=never