spring.application.name=sophia-pharmacy-service

spring.profiles.active=prod

services.medication.url=${MEDICATION_URL}
services.front.url=${FRONTEND_URL}

cors.allowed-origins=${CORS_ALLOWED_ORIGINS}

secret.key=${JWT_SECRET}
google.client.id=${GOOGLE_CLIENT_ID}

spring.mail.username=${MAIL_SENDER_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587


spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin
spring.rabbitmq.listener.simple.acknowledge-mode=manual

rabbitmq.exchange=pharmacy.exchange

rabbitmq.queue.incoming=pharmacy.incoming.queue
rabbitmq.queue.outgoing=pharmacy.outgoing.queue
rabbitmq.queue.audit=audit.queue

rabbitmq.routing.incoming=pharmacy.incoming
rabbitmq.routing.outgoing=pharmacy.outgoing
rabbitmq.routing.audit=audit

spring.rabbitmq.listener.simple.auto-startup=true

