server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://audit-loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: pharmacy-postgres-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: pharmacy-postgres-logs
          service: pharmacy
          component: postgres
          environment: local
          __path__: /var/log/postgresql/*.log
